Opentec scanner
CloudInn/ng-crud-ui pull request #120
Opened 2022-08-18 10:11 UTC by lamiselzobeidy

2022-08-18 10:35 UTC, ALaaDawood commented on projects/crud/src/lib/components/model-form/model-form.component.ts
> +            this.openOpentecPopup(link);
@lamiselzobeidy please make this more generalized, if the type is dialog we can call a function called open action dialog, and generalize the dialog itself

2022-08-18 10:44 UTC, ALaaDawood commented on projects/crud/src/lib/components/model-form/model-form.component.ts
> +        const linkData = link.function();
@lamiselzobeidy let's call `function`  a more descriptive name please

2022-08-18 10:47 UTC, ALaaDawood commented on projects/crud/src/lib/components/model-form/model-form.component.ts
> +                        return f['contact_type']['id'] == 1;
@lamiselzobeidy this is too specific to user profile

2022-08-18 10:48 UTC, ALaaDawood commented on projects/crud/src/lib/components/open-tec-popup/open-tec-popup.component.html
> +</div>
@lamiselzobeidy the message and the buttons need to be generic and passed to the dialog

2022-08-18 14:00 UTC, ALaaDawood commented on projects/crud/src/lib/components/model-form/model-form.component.ts
> +        const dialogRef = this.dialog.open(ScannerComponent, {
@lamiselzobeidy let's call it actionDialog instead of ScannerComponent

2022-08-18 14:01 UTC, ALaaDawood requested changes
- dialog component name too specific.
- the part about formset is too specif to user profile

2022-08-21 14:41 UTC, Shimaa-Ibrahim approved these changes

2022-08-22 00:02 UTC, ALaaDawood approved these changes

2022-08-22 00:04 UTC, merged